import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { JotaiProvider } from "../components/jotai-provider";
import dynamic from "next/dynamic";
import TerminalWindow from "../components/TerminalWindow";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen flex items-center justify-center bg-terminalBg`}>
        <JotaiProvider>
          <div className="w-screen h-screen flex items-center justify-center bg-terminalBg">
            <TerminalWindow>{children}</TerminalWindow>
          </div>
        </JotaiProvider>
      </body>
    </html>
  );
}
