import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { JotaiProvider } from "../components/jotai-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen flex items-center justify-center bg-terminalBg`}>
        <JotaiProvider>
          <div className="w-screen h-screen flex items-center justify-center bg-terminalBg">
            <div className="bg-terminalBg text-terminalText font-mono rounded-lg shadow-lg border border-terminalBorder w-full max-w-2xl h-[90vh] flex flex-col p-0">
              {/* ウィンドウヘッダー */}
              <div className="flex items-center justify-between bg-terminalBorder bg-opacity-30 px-3 py-1 rounded-t-lg border-b border-terminalBorder select-none">
                <span className="text-xs font-bold tracking-widest"></span>
                <div className="flex gap-2">
                  <span className="w-7 h-7 rounded hover:bg-terminalBorder flex items-center justify-center text-lg text-white cursor-pointer transition" title="最小化">_</span>
                  <span className="w-7 h-7 rounded hover:bg-terminalBorder flex items-center justify-center text-lg text-white cursor-pointer transition" title="ウィンドウ">□</span>
                  <span className="w-7 h-7 rounded hover:bg-terminalBorder flex items-center justify-center text-lg text-white cursor-pointer transition" title="閉じる">×</span>
                </div>
              </div>
              {/* 一枚板のターミナル内容 */}
              <div className="flex-1 overflow-y-auto p-4">
                {children}
              </div>
            </div>
          </div>
        </JotaiProvider>
      </body>
    </html>
  );
}
